#version: '4.0'

services:
  db:
    image: mysql
    container_name: dbMA
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /data/docker/mus-db:/var/lib/mysql
    restart: always
    networks:
      - mu-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mu-network

  back:
    build: ./back
    container_name: backMA
    ports:
      - "3333:3333"
    env_file:
      - ./.env
      - ./back/.env
#    volumes:
#      - ./back:/app
    depends_on:
      - db
    networks:
      - mu-network

#   front:
#     build: ./front
#     container_name: frontMA
#     ports:
#       - "3003:3003"
# #    volumes:
# #      - ./front:/app
#     depends_on:
#       - back
#     networks:
#       - mu-network

  nginx:
    build: ./front
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - mu-network
      
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

networks:
  mu-network:
