version: '3.9'

services:
  db:
    image: mysql
    container_name: dbMA
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - mu-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mu-network

  back:
    build: ./back
    container_name: backMA
    ports:
      - "3333:3333"
    volumes:
      - ./back:/app
    depends_on:
      - db
    networks:
      - mu-network

  front:
    build: ./front
    container_name: frontMA
    ports:
      - "3003:3003"
    volumes:
      - ./front:/app
    depends_on:
      - back
    networks:
      - mu-network

networks:
  mu-network:
